DROP TABLE SOLICITUDES CASCADE CONSTRAINTS;
DROP TABLE USUARIOS CASCADE CONSTRAINTS;

CREATE TABLE USUARIOS (
                          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          username VARCHAR2(50) UNIQUE NOT NULL
);

CREATE TABLE SOLICITUDES (
                             token NUMBER PRIMARY KEY,
                             id_usuario NUMBER NOT NULL,
                             fecha_peticion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                             estado VARCHAR2(20) NOT NULL,
                             CONSTRAINT fk_usuario FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id)
);